#!/usr/bin/env bash
# Walks src/ and writes DIRECTORY.md listing every algorithm with a link to
# its source file. Intended to be run from CI on every push to main.

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

REPO_URL=$(git config --get remote.origin.url \
  | sed -E 's#git@github.com:#https://github.com/#; s#\.git$##')

OUT=DIRECTORY.md

humanise() {
  # snake_case -> Title Case With Spaces
  echo "$1" \
    | tr '_' ' ' \
    | awk '{ for (i=1; i<=NF; i++) $i = toupper(substr($i,1,1)) substr($i,2); print }'
}

{
  echo "# Directory"
  echo
  echo "_Auto-generated by \`scripts/gen_directory.sh\`. Do not edit by hand._"
  echo
  echo "Source root: [\`src/\`]($REPO_URL/blob/main/src/)"
  echo

  for cat_dir in src/*/; do
    [ -d "$cat_dir" ] || continue
    category=$(basename "$cat_dir")
    pretty=$(humanise "$category")
    echo "## $pretty"
    echo
    for f in "$cat_dir"*.rs; do
      base=$(basename "$f" .rs)
      [ "$base" = "mod" ] && continue
      pretty_algo=$(humanise "$base")
      printf -- '- [%s](%s/blob/main/%s)\n' "$pretty_algo" "$REPO_URL" "$f"
    done
    echo
  done
} > "$OUT"

echo "Wrote $OUT"
